name: Create article

on:
  workflow_dispatch:

jobs:
  create_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set current datetime as env variable
        env:
          
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        id: create_branch
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=`feature/article +'%Y%m%d%H%M%S'`
          git switch -c "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
          echo ::set-output name=branch_name::$BRANCH_NAME

      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.2.0
        shell: bash

      - name: create a article
        run: qiita new ${{ env.CURRENT_DATETIME }}
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        env:
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        with:
          branch: ${{ env.BRANCH_NAME }}
          message: "記事作成"
          add: .

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        env:
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: main
          pr_title: "記事作成"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

