name: Create article

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create new branch
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d%H%M%S"`
          echo "CURRENT_DATETIME=$DATE" >> $GITHUB_ENV
          BRANCH_NAME="feature/$DATE"
          git switch -c "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.2.0
        shell: bash

      - name: create a article
        run: qiita new ${{ env.CURRENT_DATETIME }}
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash

      - name: Add and Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "sassy.watanabe@gmail.com"
          git config --global user.name "sassy(bot)"
          git add .
          git commit -m "add article"
          git push -u origin ${{ env.BRANCH_NAME}}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            -B main \
            -t '記事作成' \
            -a ${{ github.actor }}  \
            --body ""


          

