# Please set 'QIITA_TOKEN' secret to your repository
name: Publish articles

on:
  workflow_dispatch:

jobs:
  create_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c feature/${{ env.CURRENT_DATETIME }}
          git push -u origin feature/${{ env.CURRENT_DATETIME }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.2.0
        shell: bash

      - name: create a article
        run: qiita new ${{ env.CURRENT_DATETIME }}
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: feature/${{ env.CURRENT_DATETIME }}
          message: "記事作成"
          add: .

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: feature/${{ env.CURRENT_DATETIME }}
          destination_branch: main
          pr_title: "記事作成"
          github_token: ${{ secrets.GITHUB_TOKEN }}

